#服务器端口号
server:
  port: 8080

#数据库连接
spring:
  datasource:
    url: jdbc:mysql://39.97.96.152:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tian
 #模版
  thymeleaf:
    prefix: /templates/
    mode: HTML
    encoding: utf-8
  #缓存 是否开启
    cache: false
  cache:
    type: redis

  #热部署 是否开启  spring.devtools.restart.enabled=false
  #监听目录 spring.devtools.restart.additional-paths = src/main/java

  #Redis配置
  #Redis 服务器地址配置
  redis:
    host: 127.0.0.1
    port: 6379 #Redis服务器连接端口
    database: 0 #Redis数据库索引（默认为0）
    jedis:
      pool:
        max-active: 50 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20 #连接池中的最大空闲连接
        min-idle: 2 #连接池中的最小空闲连接
    connect-timeout: 5000 #连接超时时间（毫秒）
#mybatis
#myabtis自身的一些配置，例如基本类型的别名
#mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml





